/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedReturnsRouteImport } from './routes/_authenticated/returns'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics.index'
import { Route as AuthenticatedAnalyticsCustomersRouteImport } from './routes/_authenticated/analytics.customers'
import { Route as AuthenticatedAnalyticsOperationsRouteImport } from './routes/_authenticated/analytics.operations'
import { Route as AuthenticatedAnalyticsProcurementRouteImport } from './routes/_authenticated/analytics.procurement'
import { Route as AuthenticatedAnalyticsProductsRouteImport } from './routes/_authenticated/analytics.products'
import { Route as AuthenticatedAutomationIndexRouteImport } from './routes/_authenticated/automation.index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers_.$id'
import { Route as AuthenticatedFinanceCourierSettlementsRouteImport } from './routes/_authenticated/finance.courier-settlements'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory.index'
import { Route as AuthenticatedInventoryLocationsRouteImport } from './routes/_authenticated/inventory.locations'
import { Route as AuthenticatedInventoryMovementsRouteImport } from './routes/_authenticated/inventory.movements'
import { Route as AuthenticatedInventoryStocktakesRouteImport } from './routes/_authenticated/inventory.stocktakes'
import { Route as AuthenticatedInventoryTransfersRouteImport } from './routes/_authenticated/inventory.transfers'
import { Route as AuthenticatedOperationsIndexRouteImport } from './routes/_authenticated/operations.index'
import { Route as AuthenticatedOperationsMyWorkRouteImport } from './routes/_authenticated/operations.my-work'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders.index'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedOrdersExceptionsRouteImport } from './routes/_authenticated/orders.exceptions'
import { Route as AuthenticatedOrdersFulfillmentRouteImport } from './routes/_authenticated/orders.fulfillment'
import { Route as AuthenticatedOrdersNewRouteImport } from './routes/_authenticated/orders.new'
import { Route as AuthenticatedOrdersShipmentsRouteImport } from './routes/_authenticated/orders.shipments'
import { Route as AuthenticatedOrdersVerificationRouteImport } from './routes/_authenticated/orders.verification'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products.$id'
import { Route as AuthenticatedProductsBrandsRouteImport } from './routes/_authenticated/products.brands'
import { Route as AuthenticatedProductsCategoriesRouteImport } from './routes/_authenticated/products.categories'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products.new'
import { Route as AuthenticatedReturnsIdRouteImport } from './routes/_authenticated/returns_.$id'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './routes/_authenticated/suppliers.index'
import { Route as AuthenticatedSuppliersIdRouteImport } from './routes/_authenticated/suppliers.$id'
import { Route as AuthenticatedFinanceCourierSettlementsIdRouteImport } from './routes/_authenticated/finance.courier-settlements_.$id'
import { Route as AuthenticatedInventoryStocktakesIdRouteImport } from './routes/_authenticated/inventory.stocktakes_.$id'
import { Route as AuthenticatedInventoryTransfersIdRouteImport } from './routes/_authenticated/inventory.transfers_.$id'
import { Route as AuthenticatedOrdersFulfillmentsIdRouteImport } from './routes/_authenticated/orders.fulfillments.$id'
import { Route as AuthenticatedOrdersShipmentsIdRouteImport } from './routes/_authenticated/orders.shipments_.$id'
import { Route as AuthenticatedProcurementPurchaseOrdersIndexRouteImport } from './routes/_authenticated/procurement.purchase-orders.index'
import { Route as AuthenticatedProcurementPurchaseOrdersIdRouteImport } from './routes/_authenticated/procurement.purchase-orders.$id'
import { Route as AuthenticatedProcurementPurchaseOrdersNewRouteImport } from './routes/_authenticated/procurement.purchase-orders.new'
import { Route as ApiPublicCouriersProviderWebhookRouteImport } from './routes/api/public/couriers.$provider.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReturnsRoute = AuthenticatedReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsCustomersRoute =
  AuthenticatedAnalyticsCustomersRouteImport.update({
    id: '/analytics/customers',
    path: '/analytics/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsOperationsRoute =
  AuthenticatedAnalyticsOperationsRouteImport.update({
    id: '/analytics/operations',
    path: '/analytics/operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsProcurementRoute =
  AuthenticatedAnalyticsProcurementRouteImport.update({
    id: '/analytics/procurement',
    path: '/analytics/procurement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsProductsRoute =
  AuthenticatedAnalyticsProductsRouteImport.update({
    id: '/analytics/products',
    path: '/analytics/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationIndexRoute =
  AuthenticatedAutomationIndexRouteImport.update({
    id: '/automation/',
    path: '/automation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/customers_/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceCourierSettlementsRoute =
  AuthenticatedFinanceCourierSettlementsRouteImport.update({
    id: '/finance/courier-settlements',
    path: '/finance/courier-settlements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryLocationsRoute =
  AuthenticatedInventoryLocationsRouteImport.update({
    id: '/inventory/locations',
    path: '/inventory/locations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryMovementsRoute =
  AuthenticatedInventoryMovementsRouteImport.update({
    id: '/inventory/movements',
    path: '/inventory/movements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryStocktakesRoute =
  AuthenticatedInventoryStocktakesRouteImport.update({
    id: '/inventory/stocktakes',
    path: '/inventory/stocktakes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryTransfersRoute =
  AuthenticatedInventoryTransfersRouteImport.update({
    id: '/inventory/transfers',
    path: '/inventory/transfers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsIndexRoute =
  AuthenticatedOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsMyWorkRoute =
  AuthenticatedOperationsMyWorkRouteImport.update({
    id: '/operations/my-work',
    path: '/operations/my-work',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersExceptionsRoute =
  AuthenticatedOrdersExceptionsRouteImport.update({
    id: '/orders/exceptions',
    path: '/orders/exceptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersFulfillmentRoute =
  AuthenticatedOrdersFulfillmentRouteImport.update({
    id: '/orders/fulfillment',
    path: '/orders/fulfillment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersNewRoute = AuthenticatedOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersShipmentsRoute =
  AuthenticatedOrdersShipmentsRouteImport.update({
    id: '/orders/shipments',
    path: '/orders/shipments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersVerificationRoute =
  AuthenticatedOrdersVerificationRouteImport.update({
    id: '/orders/verification',
    path: '/orders/verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsBrandsRoute =
  AuthenticatedProductsBrandsRouteImport.update({
    id: '/products/brands',
    path: '/products/brands',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsCategoriesRoute =
  AuthenticatedProductsCategoriesRouteImport.update({
    id: '/products/categories',
    path: '/products/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReturnsIdRoute = AuthenticatedReturnsIdRouteImport.update({
  id: '/returns_/$id',
  path: '/returns/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuppliersIdRoute =
  AuthenticatedSuppliersIdRouteImport.update({
    id: '/suppliers/$id',
    path: '/suppliers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceCourierSettlementsIdRoute =
  AuthenticatedFinanceCourierSettlementsIdRouteImport.update({
    id: '/finance/courier-settlements_/$id',
    path: '/finance/courier-settlements/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryStocktakesIdRoute =
  AuthenticatedInventoryStocktakesIdRouteImport.update({
    id: '/inventory/stocktakes_/$id',
    path: '/inventory/stocktakes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryTransfersIdRoute =
  AuthenticatedInventoryTransfersIdRouteImport.update({
    id: '/inventory/transfers_/$id',
    path: '/inventory/transfers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersFulfillmentsIdRoute =
  AuthenticatedOrdersFulfillmentsIdRouteImport.update({
    id: '/orders/fulfillments/$id',
    path: '/orders/fulfillments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersShipmentsIdRoute =
  AuthenticatedOrdersShipmentsIdRouteImport.update({
    id: '/orders/shipments_/$id',
    path: '/orders/shipments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementPurchaseOrdersIndexRoute =
  AuthenticatedProcurementPurchaseOrdersIndexRouteImport.update({
    id: '/procurement/purchase-orders/',
    path: '/procurement/purchase-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementPurchaseOrdersIdRoute =
  AuthenticatedProcurementPurchaseOrdersIdRouteImport.update({
    id: '/procurement/purchase-orders/$id',
    path: '/procurement/purchase-orders/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementPurchaseOrdersNewRoute =
  AuthenticatedProcurementPurchaseOrdersNewRouteImport.update({
    id: '/procurement/purchase-orders/new',
    path: '/procurement/purchase-orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCouriersProviderWebhookRoute =
  ApiPublicCouriersProviderWebhookRouteImport.update({
    id: '/api/public/couriers/$provider/webhook',
    path: '/api/public/couriers/$provider/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/analytics/customers': typeof AuthenticatedAnalyticsCustomersRoute
  '/analytics/operations': typeof AuthenticatedAnalyticsOperationsRoute
  '/analytics/procurement': typeof AuthenticatedAnalyticsProcurementRoute
  '/analytics/products': typeof AuthenticatedAnalyticsProductsRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/finance/courier-settlements': typeof AuthenticatedFinanceCourierSettlementsRoute
  '/inventory/locations': typeof AuthenticatedInventoryLocationsRoute
  '/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/inventory/stocktakes': typeof AuthenticatedInventoryStocktakesRoute
  '/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/operations/my-work': typeof AuthenticatedOperationsMyWorkRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/orders/exceptions': typeof AuthenticatedOrdersExceptionsRoute
  '/orders/fulfillment': typeof AuthenticatedOrdersFulfillmentRoute
  '/orders/new': typeof AuthenticatedOrdersNewRoute
  '/orders/shipments': typeof AuthenticatedOrdersShipmentsRoute
  '/orders/verification': typeof AuthenticatedOrdersVerificationRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/brands': typeof AuthenticatedProductsBrandsRoute
  '/products/categories': typeof AuthenticatedProductsCategoriesRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/returns/$id': typeof AuthenticatedReturnsIdRoute
  '/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/automation/': typeof AuthenticatedAutomationIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/operations/': typeof AuthenticatedOperationsIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/finance/courier-settlements/$id': typeof AuthenticatedFinanceCourierSettlementsIdRoute
  '/inventory/stocktakes/$id': typeof AuthenticatedInventoryStocktakesIdRoute
  '/inventory/transfers/$id': typeof AuthenticatedInventoryTransfersIdRoute
  '/orders/fulfillments/$id': typeof AuthenticatedOrdersFulfillmentsIdRoute
  '/orders/shipments/$id': typeof AuthenticatedOrdersShipmentsIdRoute
  '/procurement/purchase-orders/$id': typeof AuthenticatedProcurementPurchaseOrdersIdRoute
  '/procurement/purchase-orders/new': typeof AuthenticatedProcurementPurchaseOrdersNewRoute
  '/procurement/purchase-orders/': typeof AuthenticatedProcurementPurchaseOrdersIndexRoute
  '/api/public/couriers/$provider/webhook': typeof ApiPublicCouriersProviderWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/analytics/customers': typeof AuthenticatedAnalyticsCustomersRoute
  '/analytics/operations': typeof AuthenticatedAnalyticsOperationsRoute
  '/analytics/procurement': typeof AuthenticatedAnalyticsProcurementRoute
  '/analytics/products': typeof AuthenticatedAnalyticsProductsRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/finance/courier-settlements': typeof AuthenticatedFinanceCourierSettlementsRoute
  '/inventory/locations': typeof AuthenticatedInventoryLocationsRoute
  '/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/inventory/stocktakes': typeof AuthenticatedInventoryStocktakesRoute
  '/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/operations/my-work': typeof AuthenticatedOperationsMyWorkRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/orders/exceptions': typeof AuthenticatedOrdersExceptionsRoute
  '/orders/fulfillment': typeof AuthenticatedOrdersFulfillmentRoute
  '/orders/new': typeof AuthenticatedOrdersNewRoute
  '/orders/shipments': typeof AuthenticatedOrdersShipmentsRoute
  '/orders/verification': typeof AuthenticatedOrdersVerificationRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/brands': typeof AuthenticatedProductsBrandsRoute
  '/products/categories': typeof AuthenticatedProductsCategoriesRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/returns/$id': typeof AuthenticatedReturnsIdRoute
  '/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/automation': typeof AuthenticatedAutomationIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/operations': typeof AuthenticatedOperationsIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/finance/courier-settlements/$id': typeof AuthenticatedFinanceCourierSettlementsIdRoute
  '/inventory/stocktakes/$id': typeof AuthenticatedInventoryStocktakesIdRoute
  '/inventory/transfers/$id': typeof AuthenticatedInventoryTransfersIdRoute
  '/orders/fulfillments/$id': typeof AuthenticatedOrdersFulfillmentsIdRoute
  '/orders/shipments/$id': typeof AuthenticatedOrdersShipmentsIdRoute
  '/procurement/purchase-orders/$id': typeof AuthenticatedProcurementPurchaseOrdersIdRoute
  '/procurement/purchase-orders/new': typeof AuthenticatedProcurementPurchaseOrdersNewRoute
  '/procurement/purchase-orders': typeof AuthenticatedProcurementPurchaseOrdersIndexRoute
  '/api/public/couriers/$provider/webhook': typeof ApiPublicCouriersProviderWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/returns': typeof AuthenticatedReturnsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/analytics/customers': typeof AuthenticatedAnalyticsCustomersRoute
  '/_authenticated/analytics/operations': typeof AuthenticatedAnalyticsOperationsRoute
  '/_authenticated/analytics/procurement': typeof AuthenticatedAnalyticsProcurementRoute
  '/_authenticated/analytics/products': typeof AuthenticatedAnalyticsProductsRoute
  '/_authenticated/customers_/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/finance/courier-settlements': typeof AuthenticatedFinanceCourierSettlementsRoute
  '/_authenticated/inventory/locations': typeof AuthenticatedInventoryLocationsRoute
  '/_authenticated/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/_authenticated/inventory/stocktakes': typeof AuthenticatedInventoryStocktakesRoute
  '/_authenticated/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/_authenticated/operations/my-work': typeof AuthenticatedOperationsMyWorkRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/orders/exceptions': typeof AuthenticatedOrdersExceptionsRoute
  '/_authenticated/orders/fulfillment': typeof AuthenticatedOrdersFulfillmentRoute
  '/_authenticated/orders/new': typeof AuthenticatedOrdersNewRoute
  '/_authenticated/orders/shipments': typeof AuthenticatedOrdersShipmentsRoute
  '/_authenticated/orders/verification': typeof AuthenticatedOrdersVerificationRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/products/brands': typeof AuthenticatedProductsBrandsRoute
  '/_authenticated/products/categories': typeof AuthenticatedProductsCategoriesRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/returns_/$id': typeof AuthenticatedReturnsIdRoute
  '/_authenticated/suppliers/$id': typeof AuthenticatedSuppliersIdRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/automation/': typeof AuthenticatedAutomationIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/operations/': typeof AuthenticatedOperationsIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/_authenticated/finance/courier-settlements_/$id': typeof AuthenticatedFinanceCourierSettlementsIdRoute
  '/_authenticated/inventory/stocktakes_/$id': typeof AuthenticatedInventoryStocktakesIdRoute
  '/_authenticated/inventory/transfers_/$id': typeof AuthenticatedInventoryTransfersIdRoute
  '/_authenticated/orders/fulfillments/$id': typeof AuthenticatedOrdersFulfillmentsIdRoute
  '/_authenticated/orders/shipments_/$id': typeof AuthenticatedOrdersShipmentsIdRoute
  '/_authenticated/procurement/purchase-orders/$id': typeof AuthenticatedProcurementPurchaseOrdersIdRoute
  '/_authenticated/procurement/purchase-orders/new': typeof AuthenticatedProcurementPurchaseOrdersNewRoute
  '/_authenticated/procurement/purchase-orders/': typeof AuthenticatedProcurementPurchaseOrdersIndexRoute
  '/api/public/couriers/$provider/webhook': typeof ApiPublicCouriersProviderWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/returns'
    | '/settings'
    | '/.lovable/oauth/consent'
    | '/analytics/customers'
    | '/analytics/operations'
    | '/analytics/procurement'
    | '/analytics/products'
    | '/customers/$id'
    | '/finance/courier-settlements'
    | '/inventory/locations'
    | '/inventory/movements'
    | '/inventory/stocktakes'
    | '/inventory/transfers'
    | '/operations/my-work'
    | '/orders/$id'
    | '/orders/exceptions'
    | '/orders/fulfillment'
    | '/orders/new'
    | '/orders/shipments'
    | '/orders/verification'
    | '/products/$id'
    | '/products/brands'
    | '/products/categories'
    | '/products/new'
    | '/returns/$id'
    | '/suppliers/$id'
    | '/analytics/'
    | '/automation/'
    | '/customers/'
    | '/inventory/'
    | '/operations/'
    | '/orders/'
    | '/products/'
    | '/suppliers/'
    | '/finance/courier-settlements/$id'
    | '/inventory/stocktakes/$id'
    | '/inventory/transfers/$id'
    | '/orders/fulfillments/$id'
    | '/orders/shipments/$id'
    | '/procurement/purchase-orders/$id'
    | '/procurement/purchase-orders/new'
    | '/procurement/purchase-orders/'
    | '/api/public/couriers/$provider/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/returns'
    | '/settings'
    | '/.lovable/oauth/consent'
    | '/analytics/customers'
    | '/analytics/operations'
    | '/analytics/procurement'
    | '/analytics/products'
    | '/customers/$id'
    | '/finance/courier-settlements'
    | '/inventory/locations'
    | '/inventory/movements'
    | '/inventory/stocktakes'
    | '/inventory/transfers'
    | '/operations/my-work'
    | '/orders/$id'
    | '/orders/exceptions'
    | '/orders/fulfillment'
    | '/orders/new'
    | '/orders/shipments'
    | '/orders/verification'
    | '/products/$id'
    | '/products/brands'
    | '/products/categories'
    | '/products/new'
    | '/returns/$id'
    | '/suppliers/$id'
    | '/analytics'
    | '/automation'
    | '/customers'
    | '/inventory'
    | '/operations'
    | '/orders'
    | '/products'
    | '/suppliers'
    | '/finance/courier-settlements/$id'
    | '/inventory/stocktakes/$id'
    | '/inventory/transfers/$id'
    | '/orders/fulfillments/$id'
    | '/orders/shipments/$id'
    | '/procurement/purchase-orders/$id'
    | '/procurement/purchase-orders/new'
    | '/procurement/purchase-orders'
    | '/api/public/couriers/$provider/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/_authenticated/returns'
    | '/_authenticated/settings'
    | '/.lovable/oauth/consent'
    | '/_authenticated/analytics/customers'
    | '/_authenticated/analytics/operations'
    | '/_authenticated/analytics/procurement'
    | '/_authenticated/analytics/products'
    | '/_authenticated/customers_/$id'
    | '/_authenticated/finance/courier-settlements'
    | '/_authenticated/inventory/locations'
    | '/_authenticated/inventory/movements'
    | '/_authenticated/inventory/stocktakes'
    | '/_authenticated/inventory/transfers'
    | '/_authenticated/operations/my-work'
    | '/_authenticated/orders/$id'
    | '/_authenticated/orders/exceptions'
    | '/_authenticated/orders/fulfillment'
    | '/_authenticated/orders/new'
    | '/_authenticated/orders/shipments'
    | '/_authenticated/orders/verification'
    | '/_authenticated/products/$id'
    | '/_authenticated/products/brands'
    | '/_authenticated/products/categories'
    | '/_authenticated/products/new'
    | '/_authenticated/returns_/$id'
    | '/_authenticated/suppliers/$id'
    | '/_authenticated/analytics/'
    | '/_authenticated/automation/'
    | '/_authenticated/customers/'
    | '/_authenticated/inventory/'
    | '/_authenticated/operations/'
    | '/_authenticated/orders/'
    | '/_authenticated/products/'
    | '/_authenticated/suppliers/'
    | '/_authenticated/finance/courier-settlements_/$id'
    | '/_authenticated/inventory/stocktakes_/$id'
    | '/_authenticated/inventory/transfers_/$id'
    | '/_authenticated/orders/fulfillments/$id'
    | '/_authenticated/orders/shipments_/$id'
    | '/_authenticated/procurement/purchase-orders/$id'
    | '/_authenticated/procurement/purchase-orders/new'
    | '/_authenticated/procurement/purchase-orders/'
    | '/api/public/couriers/$provider/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicCouriersProviderWebhookRoute: typeof ApiPublicCouriersProviderWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/returns': {
      id: '/_authenticated/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AuthenticatedReturnsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/customers': {
      id: '/_authenticated/analytics/customers'
      path: '/analytics/customers'
      fullPath: '/analytics/customers'
      preLoaderRoute: typeof AuthenticatedAnalyticsCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/operations': {
      id: '/_authenticated/analytics/operations'
      path: '/analytics/operations'
      fullPath: '/analytics/operations'
      preLoaderRoute: typeof AuthenticatedAnalyticsOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/procurement': {
      id: '/_authenticated/analytics/procurement'
      path: '/analytics/procurement'
      fullPath: '/analytics/procurement'
      preLoaderRoute: typeof AuthenticatedAnalyticsProcurementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/products': {
      id: '/_authenticated/analytics/products'
      path: '/analytics/products'
      fullPath: '/analytics/products'
      preLoaderRoute: typeof AuthenticatedAnalyticsProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/': {
      id: '/_authenticated/automation/'
      path: '/automation'
      fullPath: '/automation/'
      preLoaderRoute: typeof AuthenticatedAutomationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers_/$id': {
      id: '/_authenticated/customers_/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/courier-settlements': {
      id: '/_authenticated/finance/courier-settlements'
      path: '/finance/courier-settlements'
      fullPath: '/finance/courier-settlements'
      preLoaderRoute: typeof AuthenticatedFinanceCourierSettlementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/locations': {
      id: '/_authenticated/inventory/locations'
      path: '/inventory/locations'
      fullPath: '/inventory/locations'
      preLoaderRoute: typeof AuthenticatedInventoryLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/movements': {
      id: '/_authenticated/inventory/movements'
      path: '/inventory/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof AuthenticatedInventoryMovementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/stocktakes': {
      id: '/_authenticated/inventory/stocktakes'
      path: '/inventory/stocktakes'
      fullPath: '/inventory/stocktakes'
      preLoaderRoute: typeof AuthenticatedInventoryStocktakesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/transfers': {
      id: '/_authenticated/inventory/transfers'
      path: '/inventory/transfers'
      fullPath: '/inventory/transfers'
      preLoaderRoute: typeof AuthenticatedInventoryTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/': {
      id: '/_authenticated/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof AuthenticatedOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/my-work': {
      id: '/_authenticated/operations/my-work'
      path: '/operations/my-work'
      fullPath: '/operations/my-work'
      preLoaderRoute: typeof AuthenticatedOperationsMyWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/exceptions': {
      id: '/_authenticated/orders/exceptions'
      path: '/orders/exceptions'
      fullPath: '/orders/exceptions'
      preLoaderRoute: typeof AuthenticatedOrdersExceptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/fulfillment': {
      id: '/_authenticated/orders/fulfillment'
      path: '/orders/fulfillment'
      fullPath: '/orders/fulfillment'
      preLoaderRoute: typeof AuthenticatedOrdersFulfillmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/new': {
      id: '/_authenticated/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthenticatedOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/shipments': {
      id: '/_authenticated/orders/shipments'
      path: '/orders/shipments'
      fullPath: '/orders/shipments'
      preLoaderRoute: typeof AuthenticatedOrdersShipmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/verification': {
      id: '/_authenticated/orders/verification'
      path: '/orders/verification'
      fullPath: '/orders/verification'
      preLoaderRoute: typeof AuthenticatedOrdersVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/brands': {
      id: '/_authenticated/products/brands'
      path: '/products/brands'
      fullPath: '/products/brands'
      preLoaderRoute: typeof AuthenticatedProductsBrandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/categories': {
      id: '/_authenticated/products/categories'
      path: '/products/categories'
      fullPath: '/products/categories'
      preLoaderRoute: typeof AuthenticatedProductsCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/returns_/$id': {
      id: '/_authenticated/returns_/$id'
      path: '/returns/$id'
      fullPath: '/returns/$id'
      preLoaderRoute: typeof AuthenticatedReturnsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers/$id': {
      id: '/_authenticated/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof AuthenticatedSuppliersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/courier-settlements_/$id': {
      id: '/_authenticated/finance/courier-settlements_/$id'
      path: '/finance/courier-settlements/$id'
      fullPath: '/finance/courier-settlements/$id'
      preLoaderRoute: typeof AuthenticatedFinanceCourierSettlementsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/stocktakes_/$id': {
      id: '/_authenticated/inventory/stocktakes_/$id'
      path: '/inventory/stocktakes/$id'
      fullPath: '/inventory/stocktakes/$id'
      preLoaderRoute: typeof AuthenticatedInventoryStocktakesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/transfers_/$id': {
      id: '/_authenticated/inventory/transfers_/$id'
      path: '/inventory/transfers/$id'
      fullPath: '/inventory/transfers/$id'
      preLoaderRoute: typeof AuthenticatedInventoryTransfersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/fulfillments/$id': {
      id: '/_authenticated/orders/fulfillments/$id'
      path: '/orders/fulfillments/$id'
      fullPath: '/orders/fulfillments/$id'
      preLoaderRoute: typeof AuthenticatedOrdersFulfillmentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/shipments_/$id': {
      id: '/_authenticated/orders/shipments_/$id'
      path: '/orders/shipments/$id'
      fullPath: '/orders/shipments/$id'
      preLoaderRoute: typeof AuthenticatedOrdersShipmentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/purchase-orders/': {
      id: '/_authenticated/procurement/purchase-orders/'
      path: '/procurement/purchase-orders'
      fullPath: '/procurement/purchase-orders/'
      preLoaderRoute: typeof AuthenticatedProcurementPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/purchase-orders/$id': {
      id: '/_authenticated/procurement/purchase-orders/$id'
      path: '/procurement/purchase-orders/$id'
      fullPath: '/procurement/purchase-orders/$id'
      preLoaderRoute: typeof AuthenticatedProcurementPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/purchase-orders/new': {
      id: '/_authenticated/procurement/purchase-orders/new'
      path: '/procurement/purchase-orders/new'
      fullPath: '/procurement/purchase-orders/new'
      preLoaderRoute: typeof AuthenticatedProcurementPurchaseOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/couriers/$provider/webhook': {
      id: '/api/public/couriers/$provider/webhook'
      path: '/api/public/couriers/$provider/webhook'
      fullPath: '/api/public/couriers/$provider/webhook'
      preLoaderRoute: typeof ApiPublicCouriersProviderWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReturnsRoute: typeof AuthenticatedReturnsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAnalyticsCustomersRoute: typeof AuthenticatedAnalyticsCustomersRoute
  AuthenticatedAnalyticsOperationsRoute: typeof AuthenticatedAnalyticsOperationsRoute
  AuthenticatedAnalyticsProcurementRoute: typeof AuthenticatedAnalyticsProcurementRoute
  AuthenticatedAnalyticsProductsRoute: typeof AuthenticatedAnalyticsProductsRoute
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedFinanceCourierSettlementsRoute: typeof AuthenticatedFinanceCourierSettlementsRoute
  AuthenticatedInventoryLocationsRoute: typeof AuthenticatedInventoryLocationsRoute
  AuthenticatedInventoryMovementsRoute: typeof AuthenticatedInventoryMovementsRoute
  AuthenticatedInventoryStocktakesRoute: typeof AuthenticatedInventoryStocktakesRoute
  AuthenticatedInventoryTransfersRoute: typeof AuthenticatedInventoryTransfersRoute
  AuthenticatedOperationsMyWorkRoute: typeof AuthenticatedOperationsMyWorkRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedOrdersExceptionsRoute: typeof AuthenticatedOrdersExceptionsRoute
  AuthenticatedOrdersFulfillmentRoute: typeof AuthenticatedOrdersFulfillmentRoute
  AuthenticatedOrdersNewRoute: typeof AuthenticatedOrdersNewRoute
  AuthenticatedOrdersShipmentsRoute: typeof AuthenticatedOrdersShipmentsRoute
  AuthenticatedOrdersVerificationRoute: typeof AuthenticatedOrdersVerificationRoute
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedProductsBrandsRoute: typeof AuthenticatedProductsBrandsRoute
  AuthenticatedProductsCategoriesRoute: typeof AuthenticatedProductsCategoriesRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedReturnsIdRoute: typeof AuthenticatedReturnsIdRoute
  AuthenticatedSuppliersIdRoute: typeof AuthenticatedSuppliersIdRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedAutomationIndexRoute: typeof AuthenticatedAutomationIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedOperationsIndexRoute: typeof AuthenticatedOperationsIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
  AuthenticatedFinanceCourierSettlementsIdRoute: typeof AuthenticatedFinanceCourierSettlementsIdRoute
  AuthenticatedInventoryStocktakesIdRoute: typeof AuthenticatedInventoryStocktakesIdRoute
  AuthenticatedInventoryTransfersIdRoute: typeof AuthenticatedInventoryTransfersIdRoute
  AuthenticatedOrdersFulfillmentsIdRoute: typeof AuthenticatedOrdersFulfillmentsIdRoute
  AuthenticatedOrdersShipmentsIdRoute: typeof AuthenticatedOrdersShipmentsIdRoute
  AuthenticatedProcurementPurchaseOrdersIdRoute: typeof AuthenticatedProcurementPurchaseOrdersIdRoute
  AuthenticatedProcurementPurchaseOrdersNewRoute: typeof AuthenticatedProcurementPurchaseOrdersNewRoute
  AuthenticatedProcurementPurchaseOrdersIndexRoute: typeof AuthenticatedProcurementPurchaseOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReturnsRoute: AuthenticatedReturnsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAnalyticsCustomersRoute: AuthenticatedAnalyticsCustomersRoute,
  AuthenticatedAnalyticsOperationsRoute: AuthenticatedAnalyticsOperationsRoute,
  AuthenticatedAnalyticsProcurementRoute:
    AuthenticatedAnalyticsProcurementRoute,
  AuthenticatedAnalyticsProductsRoute: AuthenticatedAnalyticsProductsRoute,
  AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  AuthenticatedFinanceCourierSettlementsRoute:
    AuthenticatedFinanceCourierSettlementsRoute,
  AuthenticatedInventoryLocationsRoute: AuthenticatedInventoryLocationsRoute,
  AuthenticatedInventoryMovementsRoute: AuthenticatedInventoryMovementsRoute,
  AuthenticatedInventoryStocktakesRoute: AuthenticatedInventoryStocktakesRoute,
  AuthenticatedInventoryTransfersRoute: AuthenticatedInventoryTransfersRoute,
  AuthenticatedOperationsMyWorkRoute: AuthenticatedOperationsMyWorkRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedOrdersExceptionsRoute: AuthenticatedOrdersExceptionsRoute,
  AuthenticatedOrdersFulfillmentRoute: AuthenticatedOrdersFulfillmentRoute,
  AuthenticatedOrdersNewRoute: AuthenticatedOrdersNewRoute,
  AuthenticatedOrdersShipmentsRoute: AuthenticatedOrdersShipmentsRoute,
  AuthenticatedOrdersVerificationRoute: AuthenticatedOrdersVerificationRoute,
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedProductsBrandsRoute: AuthenticatedProductsBrandsRoute,
  AuthenticatedProductsCategoriesRoute: AuthenticatedProductsCategoriesRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedReturnsIdRoute: AuthenticatedReturnsIdRoute,
  AuthenticatedSuppliersIdRoute: AuthenticatedSuppliersIdRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedAutomationIndexRoute: AuthenticatedAutomationIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedOperationsIndexRoute: AuthenticatedOperationsIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
  AuthenticatedFinanceCourierSettlementsIdRoute:
    AuthenticatedFinanceCourierSettlementsIdRoute,
  AuthenticatedInventoryStocktakesIdRoute:
    AuthenticatedInventoryStocktakesIdRoute,
  AuthenticatedInventoryTransfersIdRoute:
    AuthenticatedInventoryTransfersIdRoute,
  AuthenticatedOrdersFulfillmentsIdRoute:
    AuthenticatedOrdersFulfillmentsIdRoute,
  AuthenticatedOrdersShipmentsIdRoute: AuthenticatedOrdersShipmentsIdRoute,
  AuthenticatedProcurementPurchaseOrdersIdRoute:
    AuthenticatedProcurementPurchaseOrdersIdRoute,
  AuthenticatedProcurementPurchaseOrdersNewRoute:
    AuthenticatedProcurementPurchaseOrdersNewRoute,
  AuthenticatedProcurementPurchaseOrdersIndexRoute:
    AuthenticatedProcurementPurchaseOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicCouriersProviderWebhookRoute: ApiPublicCouriersProviderWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
